
export type AIProvider = 'google' | 'openai' | 'anthropic' | 'custom' | 'gemini';
export type AIModelType = string;

export interface AIModel {
    id: string;
    name: string;
    provider: AIProvider;
    modelId: string;
    description: string;
    icon?: string;
    isFree: boolean;
    costPerCall?: number;
    studios: AppView[];
    status: 'active' | 'deprecated' | 'maintenance';
    createdAt?: any;
    updatedAt?: any;
}

export interface AIConfig {
    provider: AIProvider;
    modelId: string;
}

export type LightingStyle = 'Natural Light' | 'Studio Light' | 'Golden Hour' | 'Blue Hour' | 'Cinematic' | 'Dramatic';
export type CameraPerspective = 'Front View' | 'Top View' | 'Side View' | '45° Angle' | 'Close-up' | 'Macro Shot';
export type AspectRatio = '1:1' | '16:9' | '9:16' | '4:3' | '3:4';

export interface CustomizationOptions {
  lightingStyle: LightingStyle;
  cameraPerspective: CameraPerspective;
}

export interface ImageFile {
  base64: string;
  mimeType: string;
  name: string;
}

export interface HistoryItem {
  image: ImageFile;
  prompt: string;
}

export interface ProjectBase {
  id: string;
  name: string;
  ownerId: string;
  studioType: AppView;
  status: 'active' | 'completed' | 'on_hold' | 'archived';
  progress: number;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  aiConfig?: AIConfig;
}

export type CreativeMode = 'classic' | 'pro' | 'experimental';

export interface CreatorStudioProject extends ProjectBase {
  productImages: ImageFile[];
  styleImages: ImageFile[];
  generatedImage: ImageFile | null;
  history: HistoryItem[];
  options: CustomizationOptions;
  prompt: string;
  isPromptAutoGenerated: boolean;
  styleDescription: string | null;
  isAnalyzingStyle: boolean;
  isLoading: boolean;
  isExpanding: boolean;
  error: string | null;
  uploadingTarget: 'product' | 'style' | null;
  translatedPrompt: string | null;
  isTranslating: boolean;
  editPrompt: string;
  isEditing: boolean;
  creativeMode: CreativeMode;
}


// --- App View ---
export interface SmartAsset {
    id: string;
    userId: string;
    file: ImageFile;
    name: string;
    type: 'image' | 'audio' | 'video' | 'text' | 'document';
    tags: string[];
    colors: string[];
    aiDescription?: string;
    category: string;
    dimensions?: { width: number; height: number };
    aspectRatio?: string;
    createdAt: any;
    updatedAt: any;
    isFavorite: boolean;
    studioSource: AppView;
    metadata?: any;
}

export interface AssistantMessage {
    id: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    timestamp: Date;
    attachments?: string[];
}

export interface AssistantSession {
    id: string;
    userId: string;
    messages: AssistantMessage[];
    updatedAt: Date;
}

export type AppView = 'creator_studio' | 'photoshoot_director' | 'prompt_studio' | 'voice_over_studio' | 'campaign_studio' | 'video_studio' | 'plan_studio' | 'edit_studio' | 'storyboard_studio' | 'marketing_studio' | 'controller_studio' | 'branding_studio' | 'admin_studio' | 'prepilot_agency_suite' | 'archives' | 'asset_library' | 'command_center' | 'calendar';

export interface PrePilotAgent {
    id: string;
    name: string;
    role: string;
    type: 'declarative' | 'engine';
    capabilities: ('python' | 'vision' | 'orchestration' | 'rest_api' | 'code_interpreter')[];
    status: 'active' | 'standby' | 'training' | 'error';
    orchestrationLogic?: string;
    metrics: { tasksCompleted: number; latency: string; uptime: number };
}

export interface PrePilotWorkflow {
    id: string;
    name: string;
    description: string;
    trigger: 'event' | 'schedule' | 'manual';
    status: 'active' | 'paused' | 'failed' | 'deploying';
    steps: { action: string; agentId?: string; status: 'pending' | 'active' | 'done'; connector?: string }[];
    connectors: string[];
}

export interface PrePilotKnowledgeSource {
    id: string;
    name: string;
    type: 'sharepoint' | 'drive' | 'sql' | 'graph' | 'web' | 'local';
    status: 'ready' | 'indexing' | 'error';
    documentCount: number;
    lastSynced: string;
}

export interface PrePilotSecurityPolicy {
    id: string;
    name: string;
    category: 'iam' | 'pii' | 'compliance' | 'network';
    severity: 'low' | 'medium' | 'high' | 'critical';
    status: 'enforced' | 'audit' | 'disabled';
}

export interface UnifiedProject extends ProjectBase {
    ownerId: string;
    studioType: AppView;
    status: 'active' | 'completed' | 'on_hold' | 'archived';
    priority: 'low' | 'medium' | 'high' | 'urgent';
    progress: number;
    description?: string;
    createdAt: any;
    updatedAt: any;
    thumbnail?: string;
    tags?: string[];
    isFavorite?: boolean;
    metadata?: any;
}

export interface AdminStudioProject extends ProjectBase {
    integrations: Integration[];
    apiLogs: ApiLog[];
    history: GlobalHistoryItem[];
    isGenerating?: boolean;
}

export interface GlobalHistoryItem {
    id: string;
    userId: string;
    userEmail: string;
    timestamp: string;
    type: 'image' | 'audio' | 'video' | 'text';
    studio: AppView;
    content: string; // URL or base64 or text
    prompt?: string;
    metadata?: any;
}

export interface Integration {
    id: string;
    name: string;
    provider: 'gemini' | 'openai' | 'anthropic' | 'custom' | 'google';
    apiKey: string;
    endpoint: string;
    status: 'active' | 'disabled' | 'error';
    lastUsed?: string;
    updatedAt: string;
}

export interface ApiLog {
    id: string;
    timestamp: string;
    service: string;
    status: number;
    responseTime?: number;
    error?: string;
    userId?: string;
}


// --- Photoshoot Director ---
export type ShotType = string;

export interface PhotoshootResult {
  shotType: ShotType;
  image: ImageFile | null;
  isLoading: boolean;
  error: string | null;
  editPrompt: string;
  isEditing: boolean;
}

export interface PhotoshootState {
  productImages: ImageFile[];
  selectedShotTypes: ShotType[];
  results: PhotoshootResult[];
  isGenerating: boolean;
  error: string | null;
  isUploading: boolean;
  customStylePrompt: string;
}

export interface PhotoshootDirectorProject extends ProjectBase, PhotoshootState {}


// --- Prompt Studio ---
export interface PromptStudioHistoryItem {
  image: ImageFile;
  instructions: string;
  generatedPrompt: string;
}

export interface PromptStudioState {
  images: ImageFile[];
  instructions: string;
  generatedPrompt: string | null;
  history: PromptStudioHistoryItem[];
  isLoading: boolean;
  isUploading: boolean;
  error: string | null;
  deconstruction?: {
    subject: string;
    lighting: string;
    composition: string;
    technical: string;
    style: string;
  } | null;
  selectedParameters?: {
    lens?: string;
    film?: string;
    lighting?: string;
    camera?: string;
  };
}

export interface PromptStudioProject extends ProjectBase, PromptStudioState {}

// --- Voice Over Studio ---
export interface AudioFile {
  base64: string;
  name: string;
}

export interface VoiceOverHistoryItem {
  audio: AudioFile;
  text: string;
  voice: string;
  style: string;
}

export interface VoiceOverStudioState {
  text: string;
  styleInstructions: string;
  selectedVoice: string;
  generatedAudio: AudioFile | null;
  isLoading: boolean;
  error: string | null;
  history: VoiceOverHistoryItem[];
  isPlaying: boolean;
  voiceGenderFilter: 'All' | 'Male' | 'Female';
  previewLoadingVoice: string | null;
  previewPlayingVoice: string | null;
}

export interface VoiceOverStudioProject extends ProjectBase, VoiceOverStudioState {}

// --- Branding Studio ---
export type BrandingResultCategory = 'Logo Construction Grid' | 'Typography Showcase' | 'Logo Color Variations' | 'Monochrome Version' |
    '3D Glass Logo' | 'Business Card Mockup' | '3D Glass App Icon' | 'Creative Pen Mockup' |
    'Merchandise (Tote Bag)' | 'Pencil Sketch Logo' | 'Notebook Mockup' | 'Waving Flag Mockup' |
    'Instagram Post Mockup' | 'TikTok View Mockup' | 'Letterhead Design' | 'Email Signature';

export interface BrandingResult {
  category: BrandingResultCategory;
  image: ImageFile | null;
  isLoading: boolean;
  isEditing: boolean;
  error: string | null;
  editPrompt: string;
}

export interface BrandingStudioState {
  logos: ImageFile[];
  isUploading: boolean;
  error: string | null;
  results: BrandingResult[];
  colors: string[];
  secondaryColors: string[];
  brandVoice: string;
  brandPersonality: string[];
  targetAudience: string;
  fontPreferences: string;
  missionStatement: string | null;
  visionStatement: string | null;
  coreValues: string[];
  brandArchetype: string | null;
  brandPersona: string | null;
  brandStory: string | null;
  competitorAnalysis: string | null;
  brandNaming: { name: string, tagline: string, logic: string }[] | null;
  brandManual: string | null;
  typography: { primary: string, secondary: string } | null;
  isAnalyzing: boolean;
  isGenerating: boolean;
  isGeneratingNaming: boolean;
  aspectRatio: AspectRatio;
  activeTab: 'strategy' | 'naming' | 'visuals' | 'mockups' | 'guidelines' | 'history';
}

export interface BrandingStudioProject extends ProjectBase, BrandingStudioState {}

// --- Campaign Studio ---
// ... (rest of file remains same)
export type CampaignScenario = string;

export interface CampaignResult {
    scenario: CampaignScenario;
    image: ImageFile | null;
    isLoading: boolean;
    error: string | null;
    editPrompt: string;
    isEditing: boolean;
}

export interface CampaignStudioState {
    productImages: ImageFile[];
    isUploading: boolean;
    isAnalyzing: boolean;
    isGenerating: boolean;
    error: string | null;
    results: CampaignResult[];
    productAnalysis: string | null;
    selectedMood: string;
    customPrompt: string;
    mode: 'auto' | 'custom';
    customIdeas: string[];
    isRefining?: boolean;
}

export interface CampaignStudioProject extends ProjectBase, CampaignStudioState {}

// --- Plan Studio ---
export interface PlanIdea {
    id: string;
    scenario: string;
    caption: string;
    tov: string;
    schedule: string;
    image: ImageFile | null;
    isLoadingImage: boolean;
    imageError: string | null;
}

export interface PlanStudioState {
    productImages: ImageFile[];
    logos: ImageFile[];
    prompt: string;
    targetMarket: string;
    dialect: string;
    categoryAnalysis: string | null;
    isAnalyzingCategory: boolean;
    pillars: { title: string, description: string }[];
    personas: { title: string, description: string, painPoints: string[] }[];
    swot: { strengths: string[], weaknesses: string[], opportunities: string[], threats: string[] };
    positioning: { valueProp: string, competitorGaps: string[], targetPricing: string };
    roadmap: { phase: string, tasks: string[] }[];
    canvas: {
        keyPartners: string[];
        keyActivities: string[];
        valueProps: string[];
        customerRelations: string[];
        segments: string[];
        channels: string[];
        costStructure: string[];
        revenueStreams: string[];
    };
    battleCards: { competitor: string, strengths: string, weaknesses: string, killShot: string }[];
    pitchDeck: { slide: string, content: string }[];
    ideas: PlanIdea[];
    isGeneratingPlan: boolean;
    isUploading: boolean;
    error: string | null;
    activeTab: 'brief' | 'strategy' | 'market' | 'architecture' | 'roadmap' | 'pitch' | 'posts' | 'history';
}

export interface PlanStudioProject extends ProjectBase, PlanStudioState {}

// --- Storyboard Studio ---
export interface StoryboardScene {
    id: string;
    sequence: number;
    description: string;
    visualPrompt: string;
    image: ImageFile | null;
    dialogue: string;
    shotType: string;
    cameraMovement: string;
    lighting: string;
    duration: string;
    notes: string;
    location: string;
    isLoading: boolean;
    error: string | null;
}

export interface StoryboardStudioState {
    projectTitle: string;
    script: string;
    visualStyle: string;
    aspectRatio: AspectRatio;
    scenes: StoryboardScene[];
    characterProfiles: string | null;
    locationGuide: string | null;
    moodboardImages: ImageFile[];
    moodboardConcepts: { title: string, description: string, prompt: string, image: ImageFile | null }[];
    isGeneratingPlan: boolean;
    isGeneratingScenes: boolean;
    isUploading: boolean;
    isPlaying: boolean;
    currentPlayIndex: number;
    error: string | null;
    activeTab: 'script' | 'board' | 'characters' | 'locations' | 'specs' | 'timeline' | 'visuals';
}

export interface StoryboardStudioProject extends ProjectBase, StoryboardStudioState {}

// --- Marketing Studio ---
export interface MarketingStudioState {
    brandType: 'new' | 'existing';
    brandName: string;
    specialty: string;
    brief: string;
    websiteLink: string;
    language: 'ar' | 'en';
    platforms: string[];
    campaignTone: string;
    campaignGoal: string;
    competitors: string;
    monthlyBudget?: string;
    competitorStrategy?: string;
    customerPainPoints?: string;
    campaignType?: string;
    
    // Detailed Research & SWOT Inputs
    marketTrends?: string;
    targetAudience?: string;
    targetDemographics?: string;
    perceivedStrengths?: string;
    perceivedWeaknesses?: string;
    perceivedOpportunities?: string;
    perceivedThreats?: string;
    
    // Competitive & Positioning
    positioningStatement?: string;
    uniqueSellingPoint?: string;
    
    // Planning
    campaignDuration?: string;
    successMetrics?: string;
    resourceRequirements?: string;
    
    // Traditional Marketing 
    traditionalChannels?: string[];
    printMediaDetails?: string;
    eventStrategy?: string;
    
    // Digital Specifics
    seoFocus?: string;
    conversionGoal?: string;
    
    activeTab?: 'strategy' | 'digital' | 'traditional' | 'research' | 'competitive' | 'swot' | 'plan' | 'content';
    
    // New Studio Modules
    marketResearch: string | null;
    competitiveStudy: string | null;
    marketingPlan: string | null;
    swotAnalysis: string | null;
    digitalStrategy: string | null;
    traditionalStrategy: string | null;
    
    result: string | null;
    adCopies: { platform: string, copy: string }[] | null;
    emailSequence: { subject: string, body: string }[] | null;
    influencerStrategy: string | null;
    contentCalendar: { day: string, topic: string, format: string }[] | null;
    socialBios: { platform: string, bio: string }[] | null;
    hashtags: string[] | null;
    customerJourney: { stage: string, action: string, message: string }[] | null;
    
    // Content & Copy Tools (evolved — 11 sections, ~132 tools)
    contentSection: string;
    contentSubTab: string;
    contentResults: Record<string, string | null>;
    contentIsGenerating: boolean;
    contentError: string | null;
    
    isGenerating: boolean;
    error: string | null;
}

export interface MarketingStudioProject extends ProjectBase, MarketingStudioState {}

// --- Edit Studio (PRO UPDATED) ---
export type BlendingMode = 'normal' | 'multiply' | 'screen' | 'overlay' | 'darken' | 'lighten' | 'color-dodge' | 'color-burn' | 'hard-light' | 'soft-light' | 'difference' | 'exclusion' | 'hue' | 'saturation' | 'color' | 'luminosity';

export interface LocalText {
    id: string; 
    name?: string;
    content: string;
    fontSize: number;
    color: string;
    fontFamily: string;
    fontWeight: string;
    x: number;
    y: number;
    isVisible: boolean;
    rotation: number;
    letterSpacing: number;
    lineHeight: number;
    maxWidth: number;
    opacity: number;
    blendMode: BlendingMode;
    strokeWidth: number;
    strokeColor: string;
    shadowColor: string;
    shadowBlur: number;
    shadowOffsetX: number;
    shadowOffsetY: number;
    skewX: number;
    isUppercase: boolean;
    zIndex: number;
    isLocked?: boolean;
}

export interface GlobalLayer {
    id: string;
    name?: string;
    type: 'image' | 'shape';
    file?: ImageFile;
    shapeType?: 'rect' | 'circle' | 'line' | 'star';
    scale: number;
    flipX?: boolean;
    flipY?: boolean;
    x: number;
    y: number;
    rotation: number;
    opacity: number;
    blendMode: BlendingMode;
    color?: string;
    borderRadius?: number;
    zIndex: number;
    isVisible: boolean;
    brightness?: number;
    contrast?: number;
    saturation?: number;
    blur?: number;
    dropShadowColor?: string;
    dropShadowBlur?: number;
    dropShadowX?: number;
    dropShadowY?: number;
    isLocked?: boolean;
}

export interface EditAdjustments {
    sharpness: number;
    lut: string; 
    grain: number;
    vignette: number;
    blur: number;
    contrast: number;
    saturation: number;
    exposure?: number;
    warmth?: number;
    tint?: number;
    shadows?: number;
    highlights?: number;
}

export interface DrawPath {
    id: string;
    points: { x: number, y: number }[];
    color: string;
    width: number;
    opacity: number;
    blendMode: BlendingMode;
}

export interface SliceRect {
    id: string;
    x: number;
    y: number;
    w: number;
    h: number;
    label: string;
}

export interface PenPath {
    id: string;
    points: { x: number, y: number, c1?: {x:number, y:number}, c2?: {x:number, y:number} }[];
    isClosed: boolean;
}

// Added EditStudioState to define missing state properties for EditStudioProject
export interface EditStudioState {
    baseImages: ImageFile[];
    localTexts: { [key: number]: LocalText[] };
    committedTexts: { [key: number]: LocalText[] };
    globalLayers: GlobalLayer[];
    drawings: { [key: number]: DrawPath[] };
    slices: { [key: number]: SliceRect[] };
    paths: { [key: number]: PenPath[] };
    adjustments: EditAdjustments;
    isUploading: boolean;
    error: string | null;
    activeCanvasSize: 'original' | 'instagram-post' | 'instagram-story' | 'linkedin-banner';
    undoStack: { data: any, label: string }[];
    redoStack: { data: any, label: string }[];
    isProcessingAI: boolean;
}

export interface EditStudioProject extends ProjectBase, EditStudioState {}

// --- Controller Studio ---
// Fix: Added missing types for Controller Studio
export type ControlCategory = 'Face' | 'Head' | 'Body' | 'Retouch';

export interface ControllerSlider {
    id: string;
    label: string;
    value: number;
    min: number;
    max: number;
    step: number;
    category: ControlCategory;
}

export interface ControllerStudioProject extends ProjectBase {
    sourceImages: ImageFile[];
    generatedImage: ImageFile | null;
    sliders: ControllerSlider[];
    activeCategory: ControlCategory;
    isGenerating: boolean;
    isUploading: boolean;
    error: string | null;
    history: HistoryItem[];
}


// --- PrePilot Agency Suite ---
export interface PrePilotClient {
    id: string;
    name: string;
    industry: string;
    status: 'active' | 'onboarding' | 'dormant';
    logo?: ImageFile;
}

export interface PrePilotCampaign {
    id: string;
    clientId: string;
    name: string;
    budget: string;
    startDate: string;
    endDate: string;
    status: 'planning' | 'live' | 'completed' | 'paused';
    progress: number;
    kpis: { metric: string, target: string, current: string }[];
}

export interface PrePilotLead {
    id: string;
    company: string;
    contactName: string;
    value: string;
    stage: 'lead' | 'qualified' | 'proposal' | 'negotiation' | 'closed';
    lastContact: string;
    probability: number;
}

export interface PrePilotTeamMember {
    id: string;
    name: string;
    role: string;
    department: 'creative' | 'strategy' | 'tech' | 'management';
    availability: number; // percentage
    avatar?: string;
}

export interface PrePilotAgencySuiteState {
    clients: PrePilotClient[];
    campaigns: PrePilotCampaign[];
    agents: PrePilotAgent[];
    workflows: PrePilotWorkflow[];
    leads: PrePilotLead[];
    team: PrePilotTeamMember[];
    knowledgeBases: PrePilotKnowledgeSource[];
    securityPolicies: PrePilotSecurityPolicy[];
    activeTab: 'overview' | 'clients' | 'campaigns' | 'crm' | 'team' | 'agents' | 'workflows' | 'knowledge' | 'governance' | 'strategy' | 'pilots' | 'financials' | 'system';
    isGenerating: boolean;
    error: string | null;
    strategicGoal: string;
    marketAnalysis: string | null;
    pilotResults: { id: string, name: string, confidence: number, risk: string, outcome: string }[];
    billingData: { date: string; cost: number }[];
    systemLogs: { timestamp: string; level: 'info' | 'warn' | 'error'; message: string }[];
}

export interface PrePilotAgencySuiteProject extends ProjectBase, PrePilotAgencySuiteState {}
